# 2FA plugin
#
# If you somehow can't set it up or experience any performance related issues, don't hesitate to contact me on; https://discord.gg/zgKr2YM

Creator: '2FA Plugin on spigot'

TimeForAuthentication: 1200

AllowedCommands:
  - '/2fa'