name: 2FASpigot
description: Enter a code from your device to use this plugin
version: 0.15
main: me.kyllian.TFA.TFAPlugin

commands:
  2FA:
    usage: /<command>
    description: Base command of the plugin